// <auto-generated />
using System;
using Keyworks.Persistence.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Keyworks.Persistence.Migrations
{
    [DbContext(typeof(KeyworksContext))]
    [Migration("20220722212136_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Keyworks.Domain.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPrevisao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipe")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProjeto")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Previsto")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SituacaoCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TituloId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SituacaoCardId");

                    b.HasIndex("StatusCardId");

                    b.HasIndex("TituloId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Keyworks.Domain.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Keyworks.Domain.PainelCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdemCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosicaoHorizontal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosicaoVertical")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SituacaoCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("SituacaoCardId");

                    b.ToTable("PainelCards");
                });

            modelBuilder.Entity("Keyworks.Domain.SituacaoCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SituacaoCards");
                });

            modelBuilder.Entity("Keyworks.Domain.StatusCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatusCards");
                });

            modelBuilder.Entity("Keyworks.Domain.Titulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Titulos");
                });

            modelBuilder.Entity("Keyworks.Domain.Card", b =>
                {
                    b.HasOne("Keyworks.Domain.SituacaoCard", "SituacaoCard")
                        .WithMany()
                        .HasForeignKey("SituacaoCardId");

                    b.HasOne("Keyworks.Domain.StatusCard", "StatusCard")
                        .WithMany()
                        .HasForeignKey("StatusCardId");

                    b.HasOne("Keyworks.Domain.Titulo", "Titulo")
                        .WithMany()
                        .HasForeignKey("TituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SituacaoCard");

                    b.Navigation("StatusCard");

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("Keyworks.Domain.PainelCards", b =>
                {
                    b.HasOne("Keyworks.Domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keyworks.Domain.SituacaoCard", "SituacaoCard")
                        .WithMany()
                        .HasForeignKey("SituacaoCardId");

                    b.Navigation("Card");

                    b.Navigation("SituacaoCard");
                });
#pragma warning restore 612, 618
        }
    }
}
