// <auto-generated />
using System;
using Keyworks.Persistence.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Keyworks.Persistence.Migrations
{
    [DbContext(typeof(KeyworksContext))]
    partial class KeyworksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Keyworks.Domain.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPrevisao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipe")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProjeto")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Previsto")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SituacaoCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TituloId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SituacaoCardId");

                    b.HasIndex("StatusCardId");

                    b.HasIndex("TituloId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Keyworks.Domain.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colaboradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Afonso",
                            Sobrenome = "Solano"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Pedro",
                            Sobrenome = "Henrique"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Wellington",
                            Sobrenome = "Oliveira"
                        });
                });

            modelBuilder.Entity("Keyworks.Domain.PainelCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosicaoHorizontal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosicaoVertical")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PainelCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PosicaoHorizontal = 0,
                            PosicaoVertical = 0,
                            SituacaoId = 1
                        },
                        new
                        {
                            Id = 2,
                            PosicaoHorizontal = 1,
                            PosicaoVertical = 0,
                            SituacaoId = 2
                        },
                        new
                        {
                            Id = 3,
                            PosicaoHorizontal = 2,
                            PosicaoVertical = 0,
                            SituacaoId = 3
                        },
                        new
                        {
                            Id = 4,
                            PosicaoHorizontal = 3,
                            PosicaoVertical = 0,
                            SituacaoId = 4
                        },
                        new
                        {
                            Id = 5,
                            PosicaoHorizontal = 4,
                            PosicaoVertical = 0,
                            SituacaoId = 4
                        });
                });

            modelBuilder.Entity("Keyworks.Domain.SituacaoCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PainelCardsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PainelCardsId");

                    b.ToTable("SituacaoCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Aguardando"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Em Adamento"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Pendência"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Finalizado"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Outros"
                        });
                });

            modelBuilder.Entity("Keyworks.Domain.StatusCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatusCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Em Dia"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Atenção"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Em Atraso"
                        });
                });

            modelBuilder.Entity("Keyworks.Domain.Titulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Titulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Desenvolvimento"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "UX|UI"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Financeiro"
                        });
                });

            modelBuilder.Entity("Keyworks.Domain.Card", b =>
                {
                    b.HasOne("Keyworks.Domain.SituacaoCard", "SituacaoCard")
                        .WithMany()
                        .HasForeignKey("SituacaoCardId");

                    b.HasOne("Keyworks.Domain.StatusCard", "StatusCard")
                        .WithMany()
                        .HasForeignKey("StatusCardId");

                    b.HasOne("Keyworks.Domain.Titulo", "Titulo")
                        .WithMany()
                        .HasForeignKey("TituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SituacaoCard");

                    b.Navigation("StatusCard");

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("Keyworks.Domain.SituacaoCard", b =>
                {
                    b.HasOne("Keyworks.Domain.PainelCards", "PainelCards")
                        .WithMany("SituacaoCard")
                        .HasForeignKey("PainelCardsId");

                    b.Navigation("PainelCards");
                });

            modelBuilder.Entity("Keyworks.Domain.PainelCards", b =>
                {
                    b.Navigation("SituacaoCard");
                });
#pragma warning restore 612, 618
        }
    }
}
